branches:
  except:
  - public
language: go
go:
- 1.7
sudo: required
dist: trusty
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - SSH_KEY="travis_key"
  - GIT_NAME="netboy"
  - GIT_EMAIL="netboy@mit.edu"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="master"
before_install:
- openssl aes-256-cbc -K $encrypted_3c95cbedf40a_key -iv $encrypted_3c95cbedf40a_iv
  -in travis_key.enc -out travis_key -d
before_script:
- go get -u github.com/kardianos/govendor
- go get -u github.com/gohugoio/hugo
- cd $GOPATH/src/github.com/gohugoio/hugo && govendor sync && go install
- cd $HOME/gopath/src/github.com/tep-xi/static-fp
script:
- git clone https://github.com/ggilmore/hugo-base16-theme ./themes/base16
- hugo
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=tepxi/static-fp
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- ./scripts/deploy.sh
