baseurl = "http://tep.mit.edu"
languageCode = "en-us"
title = "tEp"
theme = "base16"

# home page
[[menu.main]]
    name="tEp"
    url=""
    weight=-100 # ensure this is the left-most link

[[menu.main]]
    name="rush"
    url="rush/"
    weight=-99 # second thing

[[menu.main]]
    name="the gospel"
    url="the-gospel/"

[[menu.main]]
    name="tour"
    url="tour/"


[[menu.main]]
    name="contact/social"
    url="contact/"
    weight=100 # ensure this is the right-most link

#Other tep sites
[[menu.other_sites]]
    name="squidnet"
    url="squidnet/"
    weight=-100 # extremely important that squidnet be first site

[[menu.other_sites]]
    name="ola"
    url="ola/"

[[menu.other_sites]]
    name="lates"
    url="lates/"

[[menu.other_sites]]
    name="t.e.p.s."
    url="teps/"

[[menu.other_sites]]
    name="internal wiki"
    url="wiki/"